<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ReportViewerControl</name>
   <tag></tag>
   <elementGuidId>0e763215-e1cd-48ba-a95b-1fa5d875aa13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReportViewerControl_ctl04_ctl00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReportViewerControl_ctl04_ctl00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab99c77c-0d81-40ec-9bd4-e17d384354f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6206a722-d4a5-41f8-8524-df9a56f6050f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReportViewerControl$ctl04$ctl00</value>
      <webElementGuid>cc938c21-3156-4574-8b80-b4537eab7ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View Report</value>
      <webElementGuid>0eeb177f-8edb-4c63-9b12-d246cccede5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReportViewerControl_ctl04_ctl00</value>
      <webElementGuid>d3269477-82dc-44ad-bba7-1c1af53f1fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportViewerControl_ctl04_ctl00&quot;)</value>
      <webElementGuid>dcdfb2b7-32b9-45db-a5b6-70a653e8a960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Report template - SQL Server 2017 Reporting Services/iframe_Report template_viewer</value>
      <webElementGuid>cd405fa6-e6ef-41b2-9dc1-3b0a94a5bf4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReportViewerControl_ctl04_ctl00']</value>
      <webElementGuid>f97731a7-9d00-404d-bd1a-b1e3f3aaeb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ParameterTable_ReportViewerControl_ctl04']/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>94e6f6e4-b648-45c7-be0a-ccb85bb2250f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>5a3a6265-da84-42a1-9f88-4f6da023fdbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ReportViewerControl$ctl04$ctl00' and @id = 'ReportViewerControl_ctl04_ctl00']</value>
      <webElementGuid>cd539ba2-1722-4e70-8b51-5009eb3b80cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
