<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Report template_viewer</name>
   <tag></tag>
   <elementGuidId>ecd4e536-826b-45b5-89d5-8b15ad1c9422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div/paginated-report-viewer/div/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.viewer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>07285501-6607-4099-92b2-14cf75ba0efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!failureReason</value>
      <webElementGuid>6ac6a1de-b40c-4cc7-9689-cc2c5ed2578d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seamless</name>
      <type>Main</type>
      <value>seamless</value>
      <webElementGuid>81f78bea-ec2e-4137-b90d-331b310352ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82cbe828-9c1b-463f-8f3c-77455a0a02dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>viewer</value>
      <webElementGuid>dc84b53c-3183-41d8-b7f6-ccdf0c8ec3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FReport%20template&amp;rc:showbackbutton=true</value>
      <webElementGuid>25ada3a4-96e6-49e1-896b-979148d3aa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FReport%20template&amp;rc:showbackbutton=true</value>
      <webElementGuid>8181171e-2997-4f8f-b5ea-e0f240fb6be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;view ng-scope&quot;]/paginated-report-viewer[@class=&quot;ng-scope&quot;]/div[@class=&quot;viewerContentContainer showChrome&quot;]/div[1]/div[@class=&quot;frame&quot;]/iframe[@class=&quot;viewer&quot;]</value>
      <webElementGuid>e2be1930-bfb5-42e7-962b-94b6fec097b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/paginated-report-viewer/div/div/div/iframe</value>
      <webElementGuid>27abdac7-50fe-4c7f-8d09-61bfc7dfd65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4bbe7e85-22b1-4dec-a918-22d548a0c7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FReport%20template&amp;rc:showbackbutton=true']</value>
      <webElementGuid>61d5aa02-7373-4489-9788-9d55f848001a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
