<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_of_ReportViewerControl_ctl05_ctl05_ctl00_ctl00_ctl00</name>
   <tag></tag>
   <elementGuidId>8e3bf552-0652-484c-9b92-e1d3bdea813a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ReportViewerControl_ctl05_ctl05_ctl00_ctl00_ctl00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReportViewerControl_ctl05_ctl05_ctl00_ctl00_ctl00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb77c92a-b6ed-4177-b370-ed184f086b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReportViewerControl_ctl05_ctl05_ctl00_ctl00_ctl00</value>
      <webElementGuid>89629974-992e-433a-81eb-7c3b46da9bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphui glyphui-refresh</value>
      <webElementGuid>81cc73c5-dc9c-42bc-8144-d3d2e6ede624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportViewerControl_ctl05_ctl05_ctl00_ctl00_ctl00&quot;)</value>
      <webElementGuid>ee035f2b-0dbf-405d-ba0c-de8d3152256b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Report template - SQL Server 2017 Reporting Services/iframe_Report template_viewer</value>
      <webElementGuid>5e814f04-4a0d-484c-a382-11545eb8a2fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ReportViewerControl_ctl05_ctl05_ctl00_ctl00_ctl00']</value>
      <webElementGuid>d136ddfc-30d7-488b-9c74-e76d811f7cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReportViewerControl_ctl05_ctl05_ctl00_ctl00']/table/tbody/tr/td/span</value>
      <webElementGuid>3220de0c-66ab-42c8-a94a-e20a906eb265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div/div/table/tbody/tr/td/span</value>
      <webElementGuid>762d6c6f-abce-4dec-8ea6-48eb148c3489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ReportViewerControl_ctl05_ctl05_ctl00_ctl00_ctl00']</value>
      <webElementGuid>a4ec6f8a-34b5-444f-89e4-2e0716f2f61c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
