<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ReportViewerControlctl04ctl00</name>
   <tag></tag>
   <elementGuidId>2a844e11-6657-461c-aa44-443d1e67b9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @name = 'ReportViewerControl$ctl04$ctl00' and @id = 'ReportViewerControl_ctl04_ctl00' and @ref_element = 'Object Repository/Page_Activitate clienti - SQL Server 2017 R_a8c950/iframe_Activitate clienti_viewer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReportViewerControl_ctl04_ctl00</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReportViewerControl_ctl04_ctl00']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afab5ce0-5213-4496-a210-6eec63c562e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2d9479a8-f53b-4a2d-b056-448c85df1292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReportViewerControl$ctl04$ctl00</value>
      <webElementGuid>2aec6888-d863-4483-a944-747c39adbbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View Report</value>
      <webElementGuid>02f97bdc-7ce5-405a-b719-aa42f5b71e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReportViewerControl_ctl04_ctl00</value>
      <webElementGuid>c217efc7-27c0-4b54-b26b-b607d5c935a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportViewerControl_ctl04_ctl00&quot;)</value>
      <webElementGuid>598374b2-bd83-4a63-836f-7603de87cb8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReportViewerControl_ctl04_ctl00']</value>
      <webElementGuid>3dbb717c-f006-41dd-aa08-e257b91ee738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ParameterTable_ReportViewerControl_ctl04']/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>2879ec3d-8f36-4484-ac1a-d21612d96880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>17e68be1-f01c-4a62-a32d-37e3eba87d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ReportViewerControl$ctl04$ctl00' and @id = 'ReportViewerControl_ctl04_ctl00']</value>
      <webElementGuid>1e43faa4-6111-44ef-b35e-0679614fd573</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
