<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Report template_viewer</name>
   <tag></tag>
   <elementGuidId>a6732065-b003-4be7-9c1b-7a183d7bba16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.viewer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div/paginated-report-viewer/div/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9a690e71-a6cd-46e8-988e-4c97aad20bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!failureReason</value>
      <webElementGuid>5eba96b8-ea65-4dba-8be0-93003a9ffc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seamless</name>
      <type>Main</type>
      <value>seamless</value>
      <webElementGuid>7f4ea00d-27bd-4989-b930-5c0198df95ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f3b98d7-6b6e-4ecb-93a8-7a0415562105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>viewer</value>
      <webElementGuid>8212618e-9e49-4fd0-bf67-b5a7757e68bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FReport%20template&amp;rc:showbackbutton=true</value>
      <webElementGuid>c61034d9-8572-477e-bdd9-67046aa43546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FReport%20template&amp;rc:showbackbutton=true</value>
      <webElementGuid>80cab454-a4a7-470b-ae77-e971405070e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;view ng-scope&quot;]/paginated-report-viewer[@class=&quot;ng-scope&quot;]/div[@class=&quot;viewerContentContainer showChrome&quot;]/div[1]/div[@class=&quot;frame&quot;]/iframe[@class=&quot;viewer&quot;]</value>
      <webElementGuid>332e3b8b-ce4a-4c79-a56d-a84834c8ed86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/paginated-report-viewer/div/div/div/iframe</value>
      <webElementGuid>82df23fd-a5ec-4bbc-92bd-ca8d82e9ea55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e524b29a-9af0-47ec-b041-2f3fe1e8f0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FReport%20template&amp;rc:showbackbutton=true']</value>
      <webElementGuid>df0eeda9-424b-439d-8980-4748c97e989c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
