<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Vanzari_viewer</name>
   <tag></tag>
   <elementGuidId>459fa50a-14ec-4600-bd3f-264e31c8e16d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div/paginated-report-viewer/div/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.viewer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>14873966-78ef-4b92-968a-94f9daaf7569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!failureReason</value>
      <webElementGuid>94a5f7fb-cf3b-42d7-9ff5-138f564ee350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seamless</name>
      <type>Main</type>
      <value>seamless</value>
      <webElementGuid>d86158a8-d6ad-4e6b-a84a-35464e44de84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b8889c6f-27e3-4698-ade7-77360f6cefb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>viewer</value>
      <webElementGuid>711b9d15-c70d-4e68-9b88-8b07b58421bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FVanzari&amp;rc:showbackbutton=true</value>
      <webElementGuid>0560b3d1-1606-4768-9fb4-65ab4138c0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FVanzari&amp;rc:showbackbutton=true</value>
      <webElementGuid>356c9ab2-de96-4ebe-9d9c-6fbaf9fd13a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;view ng-scope&quot;]/paginated-report-viewer[@class=&quot;ng-scope&quot;]/div[@class=&quot;viewerContentContainer showChrome&quot;]/div[1]/div[@class=&quot;frame&quot;]/iframe[@class=&quot;viewer&quot;]</value>
      <webElementGuid>b95dbcd4-f222-4130-a844-322111ec9dbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/paginated-report-viewer/div/div/div/iframe</value>
      <webElementGuid>8be7c8ea-9e54-4981-9708-aaf5aef585db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7a7d41d4-d33d-4d06-af95-fe8bdd89c7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ReportServer/Pages/ReportViewer.aspx?%2FBodyTailors%2FReports%2FVanzari&amp;rc:showbackbutton=true']</value>
      <webElementGuid>0849006e-5112-47fe-8f5a-89150e7c221f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
